version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_campus_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password_here
      MYSQL_DATABASE: campus_db
      MYSQL_USER: campus_user
      MYSQL_PASSWORD: your_strong_user_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: campus_adminer
    restart: always
    ports:
      - "8080:8080" # Access via http://localhost:8080

volumes:
  mysql_data:
    driver: local
